final_project_crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('organization/', include('organization.urls', namespace='organization')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('accounts/login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('followup/', include('followup.urls', namespace='followup')),
    path('quote/', include('quote.urls', namespace='quote')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('create/',
         views.CreateProductView.as_view(),
         name='product_create'),
    path('list/',
         views.ListProductView.as_view(),
         name='product_list'),
    path('update/<int:pk>/',
         views.UpdateProductView.as_view(),
         name='product_update'),
    path('detail/<int:pk>/',
         views.DetailProductView.as_view(),
         name='product_detail'),
]

quote/urls.py
from django.urls import path
from . import views

app_name = 'quote'

urlpatterns = [
    path('create/',
         views.QuoteCreateView.as_view(),
         name='quote_create'),
    path('list/',
         views.QuoteListView.as_view(),
         name='quote_list'),
    path('detail/<int:pk>/',
         views.QuoteDetailView.as_view(),
         name='quote_detail'),
    path('pdf/<int:quote_id>/',
         views.quote_pdf,
         name='quote_pdf'),
    path('email/<int:quote_id>/<int:organization_id>/',
         views.send_quote_to_organization,
         name='send_mail'),
]

inventory/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse

from organization.models import OrganizationProduct


class Product(models.Model):
    """
    Product Model That Has 7 Fields and a Meta Class For Configuration.
    """
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    tax = models.BooleanField(default=True)
    pdf_file = models.FileField(upload_to='files/pdf_files/%Y/%m/%d',
                                validators=[FileExtensionValidator(allowed_extensions=['pdf']), ])
    pic_file = models.FileField(upload_to='files/pic_files/%Y/%m/%d',
                                validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), ])
    technical_report = models.TextField()
    related_products = models.ManyToManyField(OrganizationProduct,
                                              related_name='related_products')

    class Meta:
        """
        Meta Class Contains ordering for order in database
        """
        ordering = ('-price', '-name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Canonical Url for access the core Class
        """
        return reverse('inventory:detail_product', self.id)

inventory/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView

from .models import *


class CreateProductView(LoginRequiredMixin, CreateView):
    """
      Class Based View For Creating Products
    """
    model = Product
    template_name = 'inventory/create.html'
    fields = ['name',
              'price',
              'tax',
              'pdf_file',
              'pic_file',
              'technical_report',
              'related_products', ]
    success_url = reverse_lazy('inventory:product_list')


class UpdateProductView(LoginRequiredMixin, UpdateView):
    """
          Class Based View For Updating Products
    """
    model = Product
    template_name = 'inventory/update.html'
    fields = ['name',
              'price',
              'tax',
              'pdf_file',
              'pic_file',
              'technical_report',
              'related_products', ]
    success_url = reverse_lazy('inventory:product_list')


class ListProductView(LoginRequiredMixin, ListView):
    """
          Class Based View For Listing Products
    """
    model = Product
    template_name = 'inventory/list.html'
    paginate_by = 15


class DetailProductView(LoginRequiredMixin, DetailView):
    """
          Class Based View For Showing Details of Products
    """
    model = Product
    template_name = 'inventory/detail.html'

templates/inventory/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Products Creating{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post" enctype="multipart/form-data">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}

templates/inventory/detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <br>
    <br>
    <a class="btn btn-info" href="{% url 'inventory:product_update' product.id %}">Update The Product</a>
    <table class="h-75 table table-hover mt-5">
        <tbody>
        <tr>
            <td>Name</td>
            <td>{{ product.name }}</td>
        </tr>
        <tr>
            <td>Price</td>
            <td>{{ product.price }}</td>
        </tr>
        <tr>
            <td>Tax</td>
            <td>{{ product.tax }}</td>
        </tr>
        <tr>
            <td>Pdf File</td>
            <td><a class="btn btn-info" href="{{ product.pdf_file.url }}">Download Pdf</a></td>
        </tr>
        <tr>
            <td>Pic File</td>
            <td><a class="btn btn-info" href="{{ product.pic_file.url }}">Download Pic</a></td>
        </tr>
        <tr>
            <td>Report</td>
            <td>{{ product.technical_report }}</td>
        </tr>
        </tbody>
    </table>
    <br>
    <h4>Related Products : </h4>
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
        </tr>
        </thead>
        <tbody>
        {% for related_product in product.related_products.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ related_product.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/inventory/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products Lists{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Product Detail</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Tax</th>
            <th scope="col">Pdf</th>
        </tr>
        </thead>
        <tbody>
        {% for product in product_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a class="btn btn-info" href="{% url 'inventory:product_detail' product.id %}">Show Product</a></td>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>
                    {% if product.tax %}
                        <img src="{% static 'assets/True.jpg'%}" alt="True Picture">
                    {% else %}
                        <img src="{% static 'assets/False.jpg'%}" alt="False Picture">
                    {% endif %}
                </td>
                <td><a class="btn btn-info" href="{{ product.pdf_file.url }}">Download Pdf</a></td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td>Total Products :</td>
            <td colspan="4"></td>
            <td>{{ product_list.count }}</td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

templates/inventory/update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Products Changing{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}