final_project_crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('organization/', include('organization.urls', namespace='organization')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('accounts/login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('followup/', include('followup.urls', namespace='followup')),
    path('quote/', include('quote.urls', namespace='quote')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

followup/urls.py
from django.urls import path

from . import views

app_name = 'followup'

urlpatterns = [
    path('report/<int:pk>/',
         views.add_report,
         name='add_report'),
]

organization/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'org_api'

router = routers.DefaultRouter()
router.register('org_api', views.OrganizationViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

organization/urls.py
from django.urls import path, include
from . import views

app_name = 'organization'

urlpatterns = [
    path('create/',
         views.CreateOrganizationView.as_view(),
         name='organization_create'),
    path('update/<int:pk>/',
         views.UpdateOrganizationView.as_view(),
         name='organization_update'),
    path('list/',
         views.ListOrganizationView.as_view(),
         name='organization_list'),
    path('detail/<int:pk>/',
         views.DetailOrganizationView.as_view(),
         name='organization_detail'),
    path('province/list/',
         views.ListProvinceView.as_view(),
         name='province_list'),
    path('province/create/',
         views.CreateProvinceView.as_view(),
         name='province_create'),
    path('province/update/<int:pk>/',
         views.UpdateProvinceView.as_view(),
         name='province_update'),
    path('api/', include('organization.api.urls', namespace='api')),
]

quote/urls.py
from django.urls import path
from . import views

app_name = 'quote'

urlpatterns = [
    path('create/',
         views.QuoteCreateView.as_view(),
         name='quote_create'),
    path('list/',
         views.QuoteListView.as_view(),
         name='quote_list'),
    path('detail/<int:pk>/',
         views.QuoteDetailView.as_view(),
         name='quote_detail'),
    path('pdf/<int:quote_id>/',
         views.quote_pdf,
         name='quote_pdf'),
    path('email/<int:quote_id>/<int:organization_id>/',
         views.send_quote_to_organization,
         name='send_mail'),
]

organization/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class Province(models.Model):
    """
    Class For Saving Provinces.
    """
    name = models.CharField(max_length=50)

    class Meta:
        """
        Meta Class Contains Ordering for order in database
        """
        ordering = ('-name',)

    def __str__(self):
        return self.name


class OrganizationProduct(models.Model):
    """
    Class for saving organizations products.
    """
    name = models.CharField(max_length=50)

    class Meta:
        """
            Meta Class Contains Ordering for order in database
        """
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Organization(models.Model):
    """
    Class for the defining organizations.
    """
    province = models.ForeignKey(Province,
                                 on_delete=models.PROTECT,
                                 related_name='organizations')
    name = models.CharField(max_length=50,
                            unique=True)
    phone = models.CharField(max_length=50,
                             validators=[RegexValidator(regex='^(\+98?)?{?(0?9[0-9]{9,9}}?)$'), ],
                             unique=True)
    workers_count = models.PositiveIntegerField(default=0)
    products = models.ManyToManyField(OrganizationProduct,
                                      related_name='organizations')

    contact_name = models.CharField(max_length=100)
    contact_phone = models.CharField(max_length=50,
                                     validators=[RegexValidator(regex='^(\+98?)?{?(0?9[0-9]{9,9}}?)$'), ])
    contact_email = models.EmailField()
    registration_date = models.DateTimeField(auto_now_add=True)
    registrar = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.PROTECT,
                                  related_name='registered_organization')

    def get_absolute_url(self):
        """
        Canonical Url for Organization Model
        :return: reverse of detail for organization
        """
        return reverse('organization:detail_organization', self.id)

    class Meta:
        """
            Meta Class Contains Ordering for order in database
        """
        ordering = ('-registration_date', '-name',)

    def __str__(self):
        return self.name

organization/forms.py
from django import forms


class ReportForm(forms.Form):
    """
    Form For Making report
    """
    report = forms.CharField(widget=forms.Textarea)

organization/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from organization.models import Organization
from .permissions import OrganizationRegistrar
from .serializer import OrganizationSerializer


class OrganizationViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Organization.objects.all()
    serializer_class = OrganizationSerializer
    permission_classes = [IsAuthenticated, OrganizationRegistrar]

organization/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from inventory.models import Product
from .models import *


class CreateOrganizationView(LoginRequiredMixin, CreateView):
    """
    a View for creating new Organizations
    """
    model = Organization
    template_name = 'organization/create.html'
    fields = [
        'province',
        'name',
        'phone',
        'workers_count',
        'products',
        'contact_name',
        'contact_phone',
        'contact_email',
    ]
    success_url = reverse_lazy('organization:organization_list')

    def form_valid(self, form):
        form.instance.registrar = self.request.user
        return super(CreateOrganizationView, self).form_valid(form)


class UpdateOrganizationView(LoginRequiredMixin, UpdateView):
    """
        a View for updating new Organizations
    """
    model = Organization
    template_name = 'organization/update.html'
    fields = [
        'province',
        'name',
        'phone',
        'workers_count',
        'products',
        'contact_name',
        'contact_phone',
        'contact_email',
    ]
    success_url = reverse_lazy('organization:organization_list')


class ListOrganizationView(LoginRequiredMixin, ListView):
    """
        a View for listing new Organizations
    """
    model = Organization
    template_name = 'organization/list.html'
    paginate_by = 15


class DetailOrganizationView(LoginRequiredMixin, DetailView):
    model = Organization
    template_name = 'organization/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailOrganizationView, self).get_context_data(**kwargs)
        context['products'] = ','.join([product.name for product in self.object.products.all()])
        ids = self.object.products.all().values_list('related_products__id', flat=True)
        context['related_products'] = Product.objects.filter(id__in=ids)
        return context


class CreateProvinceView(CreateView):
    model = Province
    template_name = 'organization/create_province.html'
    fields = ['name']
    success_url = reverse_lazy('organization:province_list')


class UpdateProvinceView(UpdateView):
    model = Province
    template_name = 'organization/update_province.html'
    fields = ['name']
    success_url = reverse_lazy('organization:organization_list')


class ListProvinceView(ListView):
    model = Province
    template_name = 'organization/list_province.html'

templates/organization/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Organization Creating{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}

templates/organization/create_province.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Province Creating{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}

templates/organization/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ organization.name }}{% endblock %}

{% block content %}
    <br>
    <br>
    <a class="btn btn-info" href="{% url 'organization:organization_update' organization.id %}">Update The
        Organization</a>
    <a class="btn btn-info" href="{% url 'followup:add_report' organization.id %}">Reports</a>
    <table class="h-75 table table-hover mt-5">
        <tbody>
        <tr>
            <td>Province</td>
            <td>{{ organization.province }}</td>
        </tr>
        <tr>
            <td>Workers</td>
            <td>{{ organization.workers_count }}</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>{{ organization.phone }}</td>
        </tr>
        <tr>
            <td>Registration Time</td>
            <td>{{ organization.registration_date }}</td>
        </tr>
        <tr>
            <td>Registrar</td>
            <td>{{ organization.registrar }}</td>
        </tr>
        <tr>
            <td>Contact Name</td>
            <td>{{ organization.contact_name }}</td>
        </tr>
        <tr>
            <td>Contact Phone</td>
            <td>{{ organization.contact_phone }}</td>
        </tr>
        <tr>
            <td>Products</td>
            <td>{{ products }}</td>
        </tr>
        </tbody>
    </table>
    <br>
    <br>
    <br>
    <h4> Related Products </h4>
    <br>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Tax</th>
            <th scope="col">Catalog</th>
        </tr>
        </thead>
        <tbody>
        {% for related_product in related_products %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ related_product.name }}</td>
                <td>{{ related_product.price }}</td>
                <td>
                    {% if related_product.tax %}
                        <img src="{% static 'assets/True.jpg' %}" alt="True Picture">
                    {% else %}
                        <img src="{% static 'assets/False.jpg' %}" alt="False Picture">
                    {% endif %}
                </td>
                <td><a href="{{ related_product.pdf_file.url }}"><img
                        src="{% static 'assets/download-icon.png' %}" alt="Download Icon"></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/organization/list.html
{% extends 'base.html' %}
{% block title %}Organization Lists{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Organization Detail</th>
            <th scope="col">Organization Name</th>
            <th scope="col">Registrar</th>
            <th scope="col">Contact</th>
            <th scope="col">Operation</th>
        </tr>
        </thead>
        <tbody>
        {% for organization in organization_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a class="btn btn-info" href="{% url 'organization:organization_detail' organization.id %}">Show Organization</a></td>
                <td>{{ organization.name }}</td>
                <td>{{ organization.registrar }}</td>
                <td>{{ organization.contact_name }}</td>
                <td><a class="btn btn-info" href="{% url 'followup:add_report' organization.id %}">Adding Report</a></td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td>Total Organizations :</td>
            <td colspan="4"></td>
            <td>{{ organization_list.count }}</td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

templates/organization/list_province.html
{% extends 'base.html' %}
{% block title %} List of Provinces {% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Province Edit</th>
            <th scope="col">Province Name</th>
        </tr>
        </thead>
        <tbody>
        {% for province in province_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a class="btn btn-info" href="{% url 'organization:province_update' province.id %}">Edit
                    Province</a></td>
                <td>{{ province.name }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <td>Total Province</td>
            <td colspan="1"></td>
            <td>{{ province_list.count }}</td>
        </tr>
        </tfoot>
    </table>
{% endblock %}

templates/organization/update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Organization Changing{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}

templates/organization/update_province.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}Province Changing{% endblock %}

{% block content %}
    <br>
    <br>
    <form method="post">
        {{ form | crispy}}
        {% csrf_token %}
        <input class="btn btn-success mt-2" type="submit" value="Save">
    </form>
{% endblock %}