final_project_crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('organization/', include('organization.urls', namespace='organization')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('accounts/login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('followup/', include('followup.urls', namespace='followup')),
    path('quote/', include('quote.urls', namespace='quote')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

quote/urls.py
from django.urls import path
from . import views

app_name = 'quote'

urlpatterns = [
    path('create/',
         views.QuoteCreateView.as_view(),
         name='quote_create'),
    path('list/',
         views.QuoteListView.as_view(),
         name='quote_list'),
    path('detail/<int:pk>/',
         views.QuoteDetailView.as_view(),
         name='quote_detail'),
    path('pdf/<int:quote_id>/',
         views.quote_pdf,
         name='quote_pdf'),
    path('email/<int:quote_id>/<int:organization_id>/',
         views.send_quote_to_organization,
         name='send_mail'),
]

quote/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from inventory.models import Product
from organization.models import Organization


class QuoteItem(models.Model):
    """
    Model For Quote Items That Has Parent Named Quote
    """
    quote = models.ForeignKey('Quote',
                              on_delete=models.PROTECT,
                              related_name='items')
    product = models.ForeignKey(Product,
                                on_delete=models.PROTECT,
                                related_name='quote_items')
    count_of_product = models.PositiveIntegerField(default=1)
    price_before_tax = models.DecimalField(max_digits=10,
                                           decimal_places=2)
    price_after_tax = models.DecimalField(max_digits=10,
                                          decimal_places=2)
    off_percent = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['price_after_tax', ]

    def __str__(self):
        return self.product.name


class Quote(models.Model):
    """
    Model Quote For Saving Quote For Every Organization.
    """
    organization = models.ForeignKey(Organization,
                                     on_delete=models.PROTECT,
                                     related_name='quotes')
    registrar = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.PROTECT,
                                  related_name='quotes')
    registration_date = models.DateTimeField(auto_now_add=True)
    updating_date = models.DateTimeField(auto_now=True)
    total_price = models.DecimalField(max_digits=11,
                                      decimal_places=2,
                                      blank=True,
                                      null=True)
    total_count = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-registration_date', ]

    def __str__(self):
        return f'Quote Number {self.id}'

    def get_absolute_url(self):
        return reverse('quote:quote_detail', self.id)

quote/forms.py
from django import forms
from django.forms import inlineformset_factory

from inventory.models import Product
from quote.models import QuoteItem, Quote


class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['organization', ]


class QuoteItemForm(forms.ModelForm):
    class Meta:
        model = QuoteItem
        fields = ['product', 'count_of_product', 'off_percent', ]


QuoteItemFormSet = inlineformset_factory(Quote,
                                         QuoteItem,
                                         form=QuoteItemForm,
                                         extra=Product.objects.count(),
                                         max_num=100)

quote/views.py
import weasyprint
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from quote.forms import QuoteItemFormSet, QuoteForm
from .models import Quote
from .utils import calculate_off, calculate_tax
from .tasks import send_quote


class QuoteCreateView(CreateView):
    """
    Class Based View For Creating Quotes By Formsets
    """
    form_class = QuoteForm
    template_name = 'quote/create.html'
    success_url = reverse_lazy('quote:quote_list')

    def get_context_data(self, **kwargs):
        context = super(QuoteCreateView, self).get_context_data(**kwargs)
        context['formset'] = QuoteItemFormSet()
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        quote_item_formset = QuoteItemFormSet(self.request.POST)
        if form.is_valid and quote_item_formset.is_valid():
            return self.form_valid(form, quote_item_formset)
        else:
            return self.form_invalid(form, quote_item_formset)

    def form_valid(self, form, quote_item_formset):
        self.object = form.save(commit=False)
        self.object.registrar = self.request.user
        self.object.save()
        quote_items = quote_item_formset.save(commit=False)
        for item in quote_items:
            item.quote = self.object
            item.price_before_tax = calculate_off(item.product.price * item.count_of_product, item.off_percent)
            item.price_after_tax = calculate_tax(item.price_before_tax, 9 if item.product.tax else 0)
            item.save()
        self.object.total_price = self.object.items.aggregate(total_price=Sum('price_after_tax'))['total_price']
        self.object.total_count = self.object.items.aggregate(total_count=Sum('count_of_product'))['total_count']
        self.object.save()
        return redirect('quote:quote_list')

    def form_invalid(self, form, quote_item_formset):
        return self.render_to_response(self.get_context_data(form=form,
                                                             quote_item_price=quote_item_formset))


class QuoteListView(ListView):
    """
    Class Based View For Listing Available Quotes
    """
    model = Quote
    template_name = 'quote/list.html'


class QuoteDetailView(DetailView):
    """
    Class Based View For Showing Details Of A Quote
    """
    model = Quote
    template_name = 'quote/detail.html'


@login_required
def quote_pdf(request, quote_id):
    """
    View For Making Pdf For Quotes
    :param request: request
    :param quote_id: id of quote
    :return:
    """
    quote = get_object_or_404(Quote, id=quote_id)

    html = render_to_string('quote/pdf_template.html',
                            {'quote': quote})

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=quote_{quote.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[
                                               weasyprint.CSS(settings.STATIC_ROOT + 'css/bootstrap.min.css'),
                                               weasyprint.CSS(settings.STATIC_ROOT + 'css/styles.css'), ])
    return response


def send_quote_to_organization(request, quote_id, organization_id):
    """
    View To Send Quotes By Contact Email Of Organization
    :param request: request
    :param quote_id: quote id
    :param organization_id: organization id
    :return: mail status
    """
    send_quote.delay(quote_id, organization_id)
    return redirect('quote:quote_list')

templates/quote/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}
    Create Quote
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <form method="post">
            {% csrf_token %}
            {{ form.non_form_errors }}
            {{ form|crispy}}
            <br>
            <br>
            {{ formset.non_form_errors }}
            {{ formset.management_form }}
            {{ formset|crispy }}
            <div class="mt-3 mb-5">
                <button type="submit" class="px-5 btn btn-info">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/quote/detail.html
{% extends 'base.html' %}
{% block title %}
    Quote Number {{ quote.id }}
{% endblock %}

{% block content %}
    <br>
    <br>
    <button class="btn btn-info noprint" onclick="window.print()">Print Pdf</button>
    <br>
    <br>
    <table class="table m-auto">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Organization</th>
            <td>{{ quote.organization.name }}</td>
        </tr>
        <tr>
            <th scope="row">Registrar</th>
            <td>{{ quote.registrar.name }}</td>
        </tr>
        <tr>
            <th scope="row">Registration Date</th>
            <td>{{ quote.registration_date }}</td>
        </tr>
        <tr>
            <th scope="row">Last Update</th>
            <td>{{ quote.updating_date }}</td>
        </tr>
        </tbody>
    </table>
    <br>
    <br>
    <h4>Items : </h4>
    <table class="table table-striped">
        <tbody>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product</th>
            <th scope="col">Discount</th>
            <th scope="col">Count</th>
            <th scope="col">Price</th>
        </tr>
        {% for item in quote.items.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ item.product.name }}</td>
                <td>{{ item.off_percent }}</td>
                <td>{{ item.count_of_product }}</td>
                <td>{{ item.price_after_tax }}</td>
            </tr>
        {% endfor %}
        <tr>
            <th scope="row">Total Count</th>
            <td colspan="2"></td>
            <td>{{ quote.total_count }}</td>
            <td>{{ quote.total_price }}</td>
        </tr>
        </tbody>
    </table>

    <style>

    </style>
{% endblock %}

templates/quote/list.html
{% extends 'base.html' %}
{% block title %}
    Quote List
{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Details</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Products</th>
            <th scope="col">Download Quote</th>
            <th scope="col">Emailing Quote</th>
        </tr>
        </thead>
        <tbody>
        {% for quote in quote_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a class="btn btn-info" href="{% url 'quote:quote_detail' quote.id %}">Show Quote</a></td>
                <td>{{ quote.organization.contact_name }}</td>
                <td>{{ quote.items.all|join:',' }}</td>
                <td><a class="btn btn-info" href="{% url 'quote:quote_pdf' quote.id %}">Download Pdf</a></td>
                <td><a class="btn btn-info" href="{% url 'quote:send_mail' quote.id quote.organization.id %}">Send
                    Email</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/quote/pdf_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">Organization</th>
        <td>{{ quote.organization.name }}</td>
    </tr>
    <tr>
        <th scope="row">Registrar</th>
        <td>{{ quote.registrar.name }}</td>
    </tr>
    <tr>
        <th scope="row">Registration Date</th>
        <td>{{ quote.registration_date }}</td>
    </tr>
    <tr>
        <th scope="row">Last Update</th>
        <td>{{ quote.updating_date }}</td>
    </tr>
    </tbody>
</table>
<br>
<br>
Items :
<br>
<table class="table table-striped">
    <tbody>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Count</th>
        <th scope="col">Price</th>
        <th scope="col">Discount</th>
    </tr>
    {% for item in quote.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.product.name }}</td>
            <td>{{ item.count_of_product }}</td>
            <td>{{ item.price_after_tax }}</td>
            <td>{{ item.off_percent }}</td>
        </tr>
    {% endfor %}
    <tr>
        <th scope="row">Total Count</th>
        <td colspan="2"></td>
        <td>{{ quote.total_count }}</td>
        <td>{{ quote.total_price }}</td>
    </tr>
    </tbody>
</table>
</body>
</html>