final_project_crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('organization/', include('organization.urls', namespace='organization')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('accounts/login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('followup/', include('followup.urls', namespace='followup')),
    path('quote/', include('quote.urls', namespace='quote')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('create/',
         views.CreateProductView.as_view(),
         name='product_create'),
    path('list/',
         views.ListProductView.as_view(),
         name='product_list'),
    path('update/<int:pk>/',
         views.UpdateProductView.as_view(),
         name='product_update'),
    path('detail/<int:pk>/',
         views.DetailProductView.as_view(),
         name='product_detail'),
]

organization/urls.py
from django.urls import path, include
from . import views

app_name = 'organization'

urlpatterns = [
    path('create/',
         views.CreateOrganizationView.as_view(),
         name='organization_create'),
    path('update/<int:pk>/',
         views.UpdateOrganizationView.as_view(),
         name='organization_update'),
    path('list/',
         views.ListOrganizationView.as_view(),
         name='organization_list'),
    path('detail/<int:pk>/',
         views.DetailOrganizationView.as_view(),
         name='organization_detail'),
    path('province/list/',
         views.ListProvinceView.as_view(),
         name='province_list'),
    path('province/create/',
         views.CreateProvinceView.as_view(),
         name='province_create'),
    path('province/update/<int:pk>/',
         views.UpdateProvinceView.as_view(),
         name='province_update'),
    path('api/', include('organization.api.urls', namespace='api')),
]

quote/urls.py
from django.urls import path
from . import views

app_name = 'quote'

urlpatterns = [
    path('create/',
         views.QuoteCreateView.as_view(),
         name='quote_create'),
    path('list/',
         views.QuoteListView.as_view(),
         name='quote_list'),
    path('detail/<int:pk>/',
         views.QuoteDetailView.as_view(),
         name='quote_detail'),
    path('pdf/<int:quote_id>/',
         views.quote_pdf,
         name='quote_pdf'),
    path('email/<int:quote_id>/<int:organization_id>/',
         views.send_quote_to_organization,
         name='send_mail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<!-- Page content wrapper-->
<div id="page-content-wrapper">
    <!-- Top navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mt-auto mt-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown m-2">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Organizations
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'organization:organization_create' %}">Create
                                    Organization</a>
                                <a class="dropdown-item" href="{% url 'organization:organization_list' %}">List
                                    Organization</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown m-2">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Provinces
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'organization:province_create' %}">Create
                                    Province</a>
                                <a class="dropdown-item" href="{% url 'organization:province_list' %}">Province
                                    Province</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown m-2">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Inventory
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'inventory:product_create' %}">Create Product</a>
                                <a class="dropdown-item" href="{% url 'inventory:product_list' %}">List Product</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown m-2">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Quotes
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'quote:quote_create' %}">Create Quote</a>
                                <a class="dropdown-item" href="{% url 'quote:quote_list' %}">List Quote</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link btn btn-success" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container-xxl">
        {% block content %}

        {% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>